version: '3.11'
services:
  app:
    build: .
    image: 299982184250.dkr.ecr.ap-northeast-1.amazonaws.com/ab3-docker-ecr/app:latest
    volumes:
      - .:/app
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app